apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: counter2
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2025-11-24_counter_helm_example.git
    path: .
    helm:
      valuesObject:
        frontendGoHost: counter2.k8s.sikademo.com
        FONT_COLOR: blue
        BACKGROUND_COLOR: lightblue
